[package]
name = "metaschema-gen"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow = "1"
near-abi = { path = "../near-abi" }
schemars = { version = "0.8.22", features = ["impl_json_schema"] }
serde_json = "1"
