[package]
name = "near-abi"
version = "0.2.0"
edition = "2021"
rust-version = "1.56.0"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/near/near-abi-rs"
description = "NEAR smart contract ABI primitives"

[dependencies]
borsh = { version = "0.9", features = ["const-generics"] }
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", optional = true }
schemars = { version = "0.8.8", features = ["impl_json_schema"] }

[dev-dependencies]
serde_json = "1"

[features]
legacy-support = ["serde_json"]
__chunked-entries = []
